create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  full_name text not null,
  phone text not null,
  role text not null default 'student',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.demo_bookings (
  id bigint generated by default as identity primary key,
  student_name text not null,
  phone text not null,
  email text not null,
  course text not null,
  preferred_date date not null,
  preferred_time text not null,
  status text default 'pending' not null,
  user_id uuid references public.users(id) on delete set null,
  admin_notes text,
  replied_at timestamptz,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  reply text,
  status text default 'pending' not null,
  replied_at timestamptz,
  created_at timestamptz default timezone('utc'::text, now()) not null
);
